<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<div class="row">    
<div class="col-sm-6">
<?php
    $select = $form->get('idEmp');
    echo $formLabel->openTag().'Empleados';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>  
</div>    

<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    

<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    