<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
 
<?php echo $this->render('layout/titulo') ?>
<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>

<?php 
$swMos = 0;
if ( ($dato["idSol"]!=$this->id) and ($dato["idSol"]>0) ){
    $swMos = 1; // Determino si no esta en la misma seleccion ya no lo muestre
} 
if ($swMos==0){
?>
        <tr>
            <td><?php echo $dato["nom_hoj"].' '.$dato['ape_hoj'] ?></td>
            <td>
                <?php // Parametros para impresion de documento 
                $this->idR = 16; // Id del reporte
                $this->idP = $dato["id"];
                echo $this->render('layout/ipdf'); // Fin parametros ?>
            </td>                                       
            <td><?php echo $dato["nomCar"] ?></td>
            <td>
            <?php 
            if ($dato["idSol"]==$this->id)  
            {  
                echo $this->render('layout/iproceso');
            }else{   
              $lect = '';
              $val = 0;
              if ($dato["idSol"]>0)
                  $val = 1;
                  $lect = '';
                  ?>                 
                <?php   
                   $select = $form->get('check1')->setAttribute("name", "ch".$dato["id"])
                                                 ->setAttribute("value", $val ) ;

                   
                   echo $this->formCheckbox($select); ?>
                   <span class="lbl"></span>
               <?php echo '<br />';   ?>            
            <?php } ?>   
            </td>
        </tr>
    <?php } 
  } ?>
        
<?php echo $this->render('layout/tabla_p') ?>

<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>  

<?php echo $this->form()->closeTag() ?>
        
        
        
<div id='resultado'><div>        
<script>      
$(function (){    
  $('.npostu').click(function(){          
     var a = $("#id").val();
     var b = $(this).attr('id');
            var parametros = {
               "idSol" : a,
               "idHoj" : b                
             };  
             $.ajax({
               data:  parametros,		 
               url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>a',
               type:  'post',
               beforeSend: function () {
                   $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>');
               },
              success:  function (response) {
                   alert("Postulado de forma correcta")                  
                   //location.reload();
              }});     
   });
  $('.postu').click(function(){    
     var a = $("#id").val();
     var b = $(this).attr('id');
   
            var parametros = {
               "idSol" : a,
               "idHoj" : b                
             };  
                   
             $.ajax({
               data:  parametros,		 
               url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>d',
               type:  'post',
               beforeSend: function () {
                   $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>');
               },
              success:  function (response) {
                   $(location).attr('href',"<?php echo $this->basePath() ?><?php echo $this->lin?>i/"+a); 
              }});
     
   });   
});
</script>
<?php echo $this->render('layout/iregresar') ?> 

<?php 
$this->ncol='null,null,';
echo $this->render('layout/tabla_tb') ?> 