<?php echo $this->render('layout/titulo') ?>


<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["fecDoc"] ?></td>
            <td><?php echo $dato["fecApr"] ?></td>
            <td><?php echo $dato["nomSed"] ?></td>
            <td><?php echo $dato["nomCar"] ?></td>
            <td>
                <?php if ($dato["estado"]==0){ ?>
                   <?php echo $this->render('layout/ipendiente') ?>
                <?php } ?>
                <?php if ($dato["estado"]==1){ ?>
                   <?php echo $this->render('layout/iaprobado') ?>                
                <?php } ?>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>i/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ipersonal') ?> </a>
            </td>
            <td>
               <?php if ($dato["estado"]==0){ ?> 
                 <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
               <?php } ?>  
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php 
$this->ncol='null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>        