<?php echo $this->render('layout/titulo') ?>

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>
<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["nit"] ?></td>
            <td><?php if ($dato["estado"]==0) 
                       echo 'Activo'; else 
                       echo 'Inactivo';  ?></td>                
            <td><?php  
                switch ($dato["tipo"]) {
                  case 1:
                     echo "EPS";
                     break;
                  case 2:
                     echo "Pensión";
                     break;
                  case 3:
                     echo "ARP";
                     break;                                         
                  case 4:
                     echo "Cesantias";
                     break;                     
                  case 5:
                     echo "Caja de compesación";
                     break;                                      
                  case 6:
                     echo "Icbf";
                     break;                                      
                  case 7:
                     echo "Sena";
                     break;                                                       
                }                                        
                    ?></td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php 
$this->ncol='null,null,null,null,';
echo $this->render('layout/tabla_tb') ?> 