<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'e/'.$this->id,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>

<div class="tabbable">
        <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4"> 
<?php foreach($this->datCc as $datos){ ?>           
	   <li><a data-toggle="tab" href="#p<?php echo $datos['id']; ?>"><i class="green icon-fighter-jet bigger-110"></i><?php echo $datos['nombre']; ?></a></li>
<?php } ?>
        </ul>


    <div class="tab-content">
      
        
<?php foreach($this->datCc as $datos){ ?>           
    <div id="p<?php echo $datos['id']; ?>" class="tab-pane in active"><!-- datos basicos -->           
        <table  class="table table-striped table-bordered table-hover" id="table_report">   
            <tr>
                <th>Cedula</th> 
                <th>Nombre</th> 
                <th>Apellido</th> 
                <th>Invitado</th>                 
            </tr>  
      <?php 
        $id = $datos['id'];
        foreach($this->datos as $dat){ ?>           
           <?php if ($dat['id']==$id){?>
            <tr>
                <td><?php echo $dat['CedEmp']; ?></td>
                <td><?php echo $dat['nombre'].' '.$dat['apellido']; ?></td>
                <td><?php echo $dat['nomCar']; ?></td> 
                <td class="col-sm-4">
                   <div class="col-sm-4"> 
                    <?php 
                    $select = $form->get('estado')->setAttribute("value", 0 )
                                         ->setAttribute("name", "inv".$dat["idEmp"])
                                         ->setAttribute("value", $dat["invitado"])
                                         ->setValueOptions(array("1"=>"Si","2"=>"No invitado"));
                    echo $formLabel->openTag();
                    echo $formLabel->closeTag();
                    echo $this->formSelect($select);                
                    echo $this->formElementErrors($select);                       
                    ?></div>
                  </td> 
            </tr>
        
        <?php } ?>            
      <?php } ?>
        </table>    
    </div>  
<?php } ?>               
        
    </div>
  </div>

<hr />
<div class="control-group">
    <?php echo ($this->formRow($form->get('comen'))); ?>
</div> 

<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>  

<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    