<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
 
<?php echo $this->render('layout/titulo') ?>
<?php foreach ($this->datPos as $dato){ ?>
<?php } ?>
    <table class="table table-striped table-bordered table-hover">
        <tr class="text-success"  >
            <td><span class="icon-ok green"> Cargo vacante :</span> <?php echo $dato['nomCar']; ?></td>
            <td><span class="icon-ok green"> Sede :</span> <?php echo $dato['nomSede']; ?></td>
        </tr>
        <tr class="text-success" >    
            <td><span class="icon-ok green"> Fecha :</span><?php echo $dato['fecDoc']; ?></td>
            <td><span class="icon-ok green"> Numero de vacantes :</span><?php echo $dato['vacantes']; ?> </td>
        </tr>
        <tr class="text-success" >    
            <td><span class="icon-ok green"></span> Aspirante :</span><?php echo $dato['cedula'].' - '.$dato['nombre'].' '.$dato['apellido']; ?></td>
            <td><span class="icon-ok green"></span> 
<div class="col-sm-6">                Estado : 
                <?php
    $select = $form->get('estado');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
    ?> </div>
</td>
        </tr>        
    </table> 

<?php echo $this->render('layout/tabla_cF') ?>
    
   <?php 
   $tit = '';
   $it  = 1;   
   $numero=1; // Id de todos los elementos
   foreach ($this->datos as $dato){ ?>
       <?php if ($tit!=$dato["nombre"]){ ?>
         <tr><td <td colspan="4"><strong><?php $tit=$dato["nombre"];$ist=1; echo $it.' '.$dato["nombre"];$it++; ?></strong></td>
        </tr>
          <?php } ?>
        <tr>
            <td>
                <?php echo ($it-1).'.'.$ist.' '.$dato["nomItem"]; $ist++; ?></td>
            <td width="20%" >
                
             <?php if ($dato["idForm"]==0){  // Predeterminado texto cuando no hay formularios anclados ?>
                <div class="col-sm-10">
              <?php echo ($this->formRow($form->get('comenN')->setAttribute("value", $dato["descripcion"])
                                                             ->setAttribute("id", $dato["idDlchq"])
                                                             ->setAttribute("name", "texto".$dato["idDlchq"])
                                                              ));
                     ?>
                </div>             
             <?php } ?>               
                
            </td>
            <td>
              <?php if ($dato["idForm"]==0){  // Predeterminado texto cuando no hay formularios anclados ?>               
                <div class="col-sm-6">
              <?php
                $select = $form->get('estado')->setAttribute("value", $dato["estado"])
                                              ->setAttribute("id", "estado".$dato["idDlchq"])                                              
                                              ->setAttribute("name", "estado".$dato["idDlchq"])
                                              ->setValueOptions(array("0"=>"---","1"=>"Cumple","2"=>"No cumple")) ;
                echo $formLabel->openTag();
                echo $formLabel->closeTag();
                echo $this->formSelect($select);                
                echo $this->formElementErrors($select);
              ?>
                </div>   
              <?php }else { 
                  // Hay formularios anclados
                  if ($dato["tipo"]==2){ // Verificacion hoja de vida
              ?>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin; ?>vp/<?php echo $dato["id"]?>">
                <span class="btn btn-primary"><i class="icon-pencil"></i><?php echo $dato["nomForm"]; ?></span></a>
              <?php                 
                 } ?>
              <?php 
                  if ($dato["tipo"]==3){ // Verificacion referencias laborales hoja de vida
                    ?>
                    <a href="<?php echo $this->basePath() ?><?php echo $this->lin; ?>vr/<?php echo $dato["id"]?>">
                    <span class="btn btn-primary"><i class="icon-pencil"></i><?php echo $dato["nomForm"]; ?></span></a>

              <?php                                      
               }
             ?>                
              <?php 
                  if ($dato["tipo"]==4){ // Verificacion cuestionario cargo
                    ?>
                    <a href="<?php echo $this->basePath() ?><?php echo $this->lin; ?>vc/<?php echo $dato["id"]?>">
                    <span class="btn btn-primary"><i class="icon-pencil"></i><?php echo $dato["nomForm"]; ?></span></a>
              <?php                                      
               }
             ?>
              <?php 
                  if ( ($dato["tipo"]==1)  ) { // Formularios libres
                    ?>
                    <a href="<?php echo $this->basePath() ?><?php echo $this->lin; ?>f/<?php echo $dato["id"]?>">
                    <span class="btn btn-primary"><i class="icon-pencil"></i><?php echo $dato["nomForm"]; ?></span></a>
              <?php                                      
               }
             ?>                
                
            <?php    
               }
             ?>   
            </td>
            <td>              

   <?php $fileElement = $form->get('image-file')->setAttribute("name","adjunto".$dato["idDlchq"] )
                                                ->setAttribute("id","adjunto".$dato["idDlchq"] ); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
   <?php echo $this->formElementErrors($fileElement); ?>                                                                                                                        
              <hr /> 
              <?php 
              $idChueq = $dato['idDlchq'];
              foreach ($this->datAdj as $dato2){ 
               if ($dato2['idDcheq']==$idChueq){ 
                   $ruta = $this->basePath()."/Datos/Talentohumano/Contratacion/".$dato["idCheq"]."/".$idChueq;
                   ?>
                <!-- Adjuntos --> 
                <a target=_blank" href="<?php echo $ruta."/".$dato2['nombre']; ?>"><?php echo $this->render('layout/iadjunto') ?>
                <?php 
                echo $dato2['nombre']; ?>
                </a>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>ida/<?php echo $dato2["id"]?>"> <?php $this->idEli = $dato2["id"]; echo $this->render('layout/ieliminar') ?> </a>
                <hr /> 
              <?php 
                 }
               } // Fin adjunto ?>                
             <?php
               if ($dato["tipo"]==3)
               { // Verificacion referencias laborales hoja de vida
                   foreach($this->datVref as $datR)                  
                   {
                       $this->idR = 23; // Id del reporte
                       $this->idP = $datR["id"];
                       echo $this->render('layout/ipdf'); // Fin parametros                   
                   }
               }
             ?>
             <?php
               if ($dato["tipo"]==4)
               { // Verificacion perfil
//                   foreach($this->datVref as $datR)                  
//                   {
                       $this->idR = 24; // Id del reporte
                       $this->idP = $this->idCheq;
                      // echo $this->render('layout/ipdf'); // Fin parametros                   
//                   }
               }
             ?>
            </td>
        </tr>
    <?php 
      $numero++; } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
       
        
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>  

<?php echo $this->form()->closeTag() ?>

        
<?php 
//$this->ncol='null,null,';
//echo $this->render('layout/tabla_tb') ?>          

<?php 
$this->lin = $this->lin.'s/'.$this->idSol;
echo $this->render('layout/iregresar') ?> 

        
<?php 
$this->idModal = "agregarMat";
$this->botModal = "Agregar material al elemento"; ?>          
<!-- VENTANA ADJUNTAR --->
<div id="<?php echo 'v'.$this->idModal ?>" title="Manejo de componentes">
  <fieldset>

	<p>
		<label for="file">Choose file</label>
		<input type="file" id="file" name="file" accept="image/jpg, image/jpeg, image/gif, image/png" />
	</p>
	<p><button id="upload">Upload</button></p>

	<p><span id="progress" class="progress progress-striped pos-rel">0%</span></p>      
      
  </fieldset>
</div>       

<script>        
function adjuntar(id)
{
    $( "#<?php echo 'v'.$this->idModal ?>" ).dialog( "open" );
}


$(function() {     
   /// VENTANA MODAL PARA COMPONENTES ////  
   $( "#<?php echo 'v'.$this->idModal ?>" ).dialog({
      autoOpen: false,
      height: 400,
      width: 500,
      modal: true,
      Cancel: function() {
          $( this ).dialog( "close" );
        }      
    });
})
</script>        
      
        
	