<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'vp/'.$this->id,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
 
<?php echo $this->render('layout/titulo') ?>

<!-- DOCUMENTO DE ESTUDIO-->
<?php foreach ($this->datSol as $dato){ ?>
<?php } ?>
    <table class="table table-striped table-bordered table-hover">
        <tr class="text-success"  >
            <td><span class="icon-ok green"> Cargo vacante :</span> <?php echo $dato['nomCar']; ?></td>
            <td><span class="icon-ok green"> Sede :</span> <?php echo $dato['nomSed']; ?></td>
        </tr>
        <tr class="text-success" >    
            <td><span class="icon-ok green"> Fecha :</span><?php echo $dato['fecDoc']; ?></td>
            <td><span class="icon-ok green"> Numero de vacantes :</span><?php echo $dato['vacantes']; ?> </td>
        </tr>
        <tr class="text-success" >    
            <td><span class="icon-ok green"> Aspirante :</span><?php echo $dato['cedula'].' - '.$dato['nombre'].' '.$dato['apellido']; ?></td>
            <td> </td>
        </tr>        
    </table> 


<div class="widget-box"> 
    <div class="widget-header">
	<h5 class="smaller">Datos del empleado </h5>
	<div class="widget-toolbar no-border">
         <ul class="nav nav-tabs" id="myTab">
	   <li><a data-toggle="tab" href="#fondos"><i class="green icon-bolt bigger-110"></i>Estudios realizados</a></li>
           <li><a data-toggle="tab" href="#clas"><i class="green icon-beaker bigger-110"></i>Experiencia laboral</a></li>           
	   <li><a data-toggle="tab" href="#contra"><i class="green icon-bullhorn bigger-110"></i>Referencias personales</a></li>           
        </ul>
    </div>
</div>

<div class="widget-body">
  <div class="widget-main padding-5">
    <div class="tab-content">                   

<div id="fondos" class="tab-pane"><!-- ESTUDIOS REALIZADOS -->           
    <?php 
$this->ttablas="Referencia, Detalles, Estado";
echo $this->render('layout/tabla_c') ?>
    
<?php     
foreach ($this->datEst as $dato){ ?>
<tr><td>       

<div class="well well-large">
           
 <h4 class="blue"> 
     <?php echo $dato['titulo']; ?>
 </h4>
 <h5>
     <?php echo $dato['nomNest']; ?>
 </h5>         
 <h6>   
     <?php echo $dato['instituto']; ?>
 </h6>    
 <h6>   
     <?php echo $dato['fecha']; ?>
 </h6>      
   </div>
</td>
<td>
  <?php echo ($this->formRow($form->get('comenN')->setAttribute("value", $dato["descripcion"])
    ->setAttribute("id", "textoE".$dato["id"])
    ->setAttribute("name", "textoE".$dato["id"])
    ->setAttribute("class", "span10")));
  ?>            
</td>
<td>
  <?php
    $select = $form->get('estado')->setAttribute("value", $dato["estado"])
        ->setAttribute("id", "estadoE".$dato["id"])
        ->setAttribute("name", "estadoE".$dato["id"])
        ->setValueOptions(array("0"=>"---","1"=>"Verificado","2"=>"No verificado")) ;    
    echo $this->formSelect($select);                
    echo $this->formElementErrors($select);    
  ?>
</td>            

</tr>
<?php } ?>    
<?php echo $this->render('layout/tabla_p') ?>
        
</div><!-- FIN ESTUDIOS REALIZADOS -->    


<div id="clas" class="tab-pane"><!-- EXPERIENCIA LABORAL --> 
    <?php 
$this->ttablas="Referencia, Detalles, Estado";
echo $this->render('layout/tabla_c') ?>
    
<?php     
foreach ($this->datExp as $dato){ ?>
<tr><td>       

<div class="well well-large">
           
 <h4 class="blue"> 
     <?php echo $dato['cargo']; ?>
 </h4>
 <h5>
     <?php echo $dato['empresa']; ?>
 </h5>         
 <h6>   
     <?php echo $dato['contacto']; ?>
 </h6>    
 <h6>   
     <?php echo $dato['telefonos']; ?>
 </h6>         
</div>
        
</td>
<td>
  <?php echo ($this->formRow($form->get('comenN')->setAttribute("value", $dato["descripcion"] )
    ->setAttribute("id", "textoL".$dato["id"])
    ->setAttribute("name", "textoL".$dato["id"])
    ->setAttribute("class", "span10")));
  ?>            
</td>
<td>
  <?php
    $select = $form->get('estado')->setAttribute("value", $dato["estado"] )
        ->setAttribute("id", "estadoL".$dato["id"])
        ->setAttribute("name", "estadoL".$dato["id"])
        ->setValueOptions(array("0"=>"---","1"=>"Verificado","2"=>"No verificado")) ;    
    echo $this->formSelect($select);                
    echo $this->formElementErrors($select);    
  ?>
</td>            

</tr>
<?php } ?>    
<?php echo $this->render('layout/tabla_p') ?>
                                                        
</div><!-- FIN EXPERIENCIA LABORAL -->    

<div id="contra" class="tab-pane"><!-- REFERENCIAS PERSONALES -->   
    <?php 
$this->ttablas="Referencia, Detalles, Estado";
echo $this->render('layout/tabla_c') ?>
    
<?php     
foreach ($this->datRef as $dato){ ?>
<tr><td>       

<div class="well well-large">
    
 <h4 class="blue"> 
     <?php echo $dato['nombres']; ?>
 </h4>
 <h5>
     <?php echo $dato['telefonos']; ?>
 </h5>         
 <h6>   
     <?php echo $dato['dirResi']; ?>
 </h6>    
 <h6>   
     <?php echo $dato['ocupacion']; ?>
 </h6>  
    
</div>
        
</td>
<td>
  <?php echo ($this->formRow($form->get('comenN')->setAttribute("value", $dato["descripcion"])
    ->setAttribute("id", "textoR".$dato["id"])
    ->setAttribute("name", "textoR".$dato["id"])
    ->setAttribute("class", "span10")));
  ?>            
</td>
<td>
  <?php
    $select = $form->get('estado')->setAttribute("value", $dato["estado"])
        ->setAttribute("id", "estadoR".$dato["id"])
        ->setAttribute("name", "estadoR".$dato["id"])
        ->setValueOptions(array("0"=>"---","1"=>"Verificado","2"=>"No verificado")) ;    
    echo $this->formSelect($select);                
    echo $this->formElementErrors($select);    
  ?>
</td>            

</tr>
<?php } ?>    
<?php echo $this->render('layout/tabla_p') ?>    
</div><!-- FIN REFERENCIAS PERSONALES -->         
   </div>
 </div>
</div>  
    
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>  
    
<?php echo $this->form()->closeTag() ?>    
        
<?php 
$this->lin = $this->lin.'i/'.$this->idCheq;
echo $this->render('layout/iregresar') ?>    