<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'f',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>

<!-- DOCUMENTO DE ESTUDIO-->
<?php foreach ($this->datSol as $dato){ ?>
<?php } ?>
    <table class="table table-striped table-bordered table-hover">
        <tr class="text-success"  >
            <td><span class="icon-ok green"> Cargo vacante :</span> <?php echo $dato['nomCar']; ?></td>
            <td><span class="icon-ok green"> Sede :</span> <?php echo $dato['nomSed']; ?></td>
        </tr>
        <tr class="text-success" >    
            <td><span class="icon-ok green"> Fecha :</span><?php echo $dato['fecDoc']; ?></td>
            <td><span class="icon-ok green"> Numero de vacantes :</span><?php echo $dato['vacantes']; ?> </td>
        </tr>
        <tr class="text-success" >    
            <td><span class="icon-ok green"> Aspirante :</span><?php echo $dato['cedula'].' - '.$dato['nombre'].' '.$dato['apellido']; ?></td>
            <td> </td>
        </tr>        
    </table> 

<?php echo $this->render('layout/tabla_c') ?>
<?php 
foreach ($this->datos as $dato){ ?>
<?php 
// Titulo
if ($dato['tipo']==1)
{
?> 
<tr>
    <td>
        <strong><?php echo $dato['nomIform']; ?></strong>
    <hr />
    </td>    
    <td></td>
    <td></td>
</tr>
<?php }// Fin titulo
else {?> 
<tr>
    <td>
        <?php echo $dato['nomIform']; ?>
    </td>    
    <td>
    <?php 
     // Lista
     if ($dato['tipo']==3)
     {
        // Armar valores  
        //echo  $dato["lista"];
        $cadena = $dato["lista"];
        $titulo='';$sw=0;
        $arreglo='';$y=1;
        for( $i=0; $i<=strlen($cadena); $i++)
        {
	    $caracter = substr($cadena,$i,1);      
            if ($caracter!=',')
                $titulo = $titulo.$caracter;
            else 
                $sw=1;         
                if ( ($sw==1) ){     
                    $arreglo[$y] = $titulo;
                    $titulo='';$sw=0;$y++;
                }
        } 
        $arreglo[$y] = $titulo;                
                //           
        $select = $form->get('estado')->setAttribute("value", 0 )
                                      ->setAttribute("name", "lista".$dato["idIform"])
                                      ->setAttribute("value", $dato["lisForm"])         
                                      ->setValueOptions($arreglo);
        echo $formLabel->openTag();
        echo $formLabel->closeTag();
        echo $this->formSelect($select);                
        echo $this->formElementErrors($select);       
          
      } // Fin lista?>   

      <?php 
        if ($dato["tipo"]==2){  // Predeterminado texto cuando no hay formularios anclados                
            echo ($this->formRow($form->get('comenN')
                            ->setAttribute("name", "res".$dato["idIform"] )
                            ->setAttribute("value", $dato["texForm"])  
                            ->setAttribute("class", ".span3" )));
      }?>                                   

      <?php
        if ($dato["tipo"]==4){ 
        // Armar valores  
        //echo  $dato["lista"];
        $cadena = $dato["lista"];
        $titulo='';$sw=0;
        $arreglo='';$y=1;
        for( $i=0; $i<=strlen($cadena); $i++)
        {
	    $caracter = substr($cadena,$i,1);      
            if ($caracter!=',')
                $titulo = $titulo.$caracter;
            else 
                $sw=1;         
                if ( ($sw==1) ){     
                    $arreglo[$y] = $titulo;
                    $titulo='';$sw=0;$y++;
                }
          } 
          $arreglo[$y] = $titulo;                
          foreach($arreglo as $chekList)
          {
             echo $chekList;
             $select = $form->get('check1')->setAttribute("name", "ch".$dato["idIform"])
                                         ->setAttribute("value", $dato["casForm"]) ;
             echo $this->formCheckbox($select); ?>
             <span class="lbl"></span>
            <?php echo '<br />'; 
          }
        }
      ?>        
        
    </td>
    <td></td>
</tr>
<?php 
  }
} ?>
<?php echo $this->render('layout/tabla_p') ?>          

        
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>          
        
<?php echo $this->form()->closeTag() ?>

<?php 
$this->lin = $this->lin.'i/'.$this->idCheq;
echo $this->render('layout/iregresar') ?>  