<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();
?>

<?php
$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>

<?php 
$this->th3  = $this->datos;
echo $this->render('layout/h3rojo') ?>


<div class="widget-box"> 
    <div class="widget-header">
	<h5 class="smaller">Datos de nomina</h5>
	<div class="widget-toolbar no-border">
         <ul class="nav nav-tabs" id="myTab">
 	   <li class="active"><a data-toggle="tab" href="#datos"><i class="green icon-edit bigger-110"></i>Datos basicos</a></li>
	   <li><a data-toggle="tab" href="#fondos"><i class="green icon-bolt bigger-110"></i>Fondos prestacionales y seguridad social</a></li>
           <li><a data-toggle="tab" href="#clas"><i class="green icon-beaker bigger-110"></i>Clasificación</a></li>           
	   <li><a data-toggle="tab" href="#contra"><i class="green icon-bullhorn bigger-110"></i>Aspectos contractuales</a></li>           
        </ul>
    </div>
</div>
	  
<div class="widget-body">
  <div class="widget-main padding-5">
    <div class="tab-content">
      <div id="datos" class="tab-pane in active"><!-- datos basicos -->   
          
<table>
<tr><td>    
<?php
    $name = $form->get('cedula');
    echo $formLabel->openTag().$name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?></td><td>
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag().'Nombres';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</td><td>        
<?php
    $name = $form->get('apellido1');
    echo $formLabel->openTag().'Apellidos';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</td></tr>
</table>

<table>
<tr><td>    
<?php
    $select = $form->get('sexo');
    echo $formLabel->openTag().'Sexo';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $name = $form->get('fecDoc');
    echo $formLabel->openTag().'Fecha de nacimiento: ';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>    
</td></tr>
</table>
<table>
<tr><td>  
<?php
    $name = $form->get('dir');
    echo $formLabel->openTag().'Dirección';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</td><td>                                                                                                     
<?php
    $name = $form->get('numero');
    echo $formLabel->openTag().'Telefono ';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</td></tr>
</table>
<table>
<tr><td>  
<?php
    $name = $form->get('email');
    echo $formLabel->openTag().'e-mail';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</td></tr>
</table>
<?php
    $name = $form->get('sueldo');
    //$name = $form->setAttribute("",true);
    echo $formLabel->openTag().' Sueldo';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>  
    


</div><!-- FIN PESTAÑA DATOS BASICOS -->    
<div id="fondos" class="tab-pane"><!-- fondos -->              
      
      
<table>
<tr><td>    
<?php
    $select = $form->get('idSal');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $select = $form->get('idPen');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $select = $form->get('idArp');
    echo $formLabel->openTag().'ARL';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td></td>
<tr><td>
<?php
    $select = $form->get('idCes');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $select = $form->get('idCaja');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $select = $form->get('idFav');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td></tr>    
</table>
<div class="form_element">
<?php
    $select = $form->get('idFafc');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>                          

</div><!-- FIN FONDOS -->    
<div id="clas" class="tab-pane"><!-- Clasificaciones -->      
    
    
<table>
<tr><td>
<?php
    $select = $form->get('idCar');
    echo $formLabel->openTag().'Cargo';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $select = $form->get('idCencos');
    echo $formLabel->openTag().'Centro de costo';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>

</td></tr>
<tr><td>
<?php
    $select = $form->get('tipo');
    echo $formLabel->openTag().'Tipo de contratación';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>       
</td><td>
    <?php
    $select = $form->get('idTemp');
    echo $formLabel->openTag().'Tipo de empleado';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td></tr>    
<tr><td>    
<?php
    $select = $form->get('idCal');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>    
</td><td>
<?php
    $select = $form->get('idPrej');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>    
</td><td>
<?php
    $select = $form->get('idGrupo');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?></td></tr>
</table>
<hr />
<table>
<tr><td>
<?php
    $select = $form->get('idTau');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $select = $form->get('idTau2');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td><td>
<?php
    $select = $form->get('idTau3');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td>
<td>
<?php
    $select = $form->get('idTau4');
    echo $formLabel->openTag().$select->getLabel('label');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td>
</tr>
</table>
                                                                         
</div><!-- FIN CLASIFICACIONES -->    
<div id="contra" class="tab-pane"><!-- Contrataciones -->  
<div class="control-group">
<?php
    $name = $form->get('fecIng')->setAttribute("readOnly",true);
    echo $formLabel->openTag().'Fecha inicio de labores';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>                                                                                                     

    <div class="form_element">
<?php
    $select = $form->get('fecPnom')->setAttribute("readOnly",true);
    echo $formLabel->openTag().'Ultimo pago de nomina';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($select);
?>
</div>                                    
    
<div class="form_element">
<?php
    $select = $form->get('fecPvac')->setAttribute("readOnly",true);
    echo $formLabel->openTag().'Ultimas vacaciones pagadas';
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($select);
?>
</div>                                            

</div>
   </div>
 </div>
</div>    

<hr />

<div class="widget-box"> 
    <div class="widget-header">
	<h5 class="smaller">Datos generales </h5>
	<div class="widget-toolbar no-border">
         <ul class="nav nav-tabs" id="myTab">
 	   <li class="active"><a data-toggle="tab" href="#cuadro"><i class="green icon-group bigger-110"></i>Cuadro familiar</a></li>             
	   <li><a data-toggle="tab" href="#fisico"><i class="green icon-edit bigger-110"></i>Estado fisico</a></li>             
           <li><a data-toggle="tab" href="#aficiones"><i class="green icon-beaker bigger-110"></i>Aficiones y gustos</a></li>           
        </ul>
    </div>
</div>
	  
<div class="widget-body">
  <div class="widget-main padding-5">
    <div class="tab-content">

      <div id="cuadro" class="tab-pane in active"><!-- Cuadro familiar -->   
            
    
      </div><!-- Fin Cuadro familiar -->           
        
      <div id="fisico" class="tab-pane in active"><!-- Estado fisico -->   
          <table>
              <tr>
                  <td>
<?php
    $select = $form->get('sangre');
    echo $formLabel->openTag().'Tipo de sangre';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
                         
                  </td>    

                  <td>
                   <?php
                     $select = $form->get('check1')->setAttribute("name", "lentes");
                     echo $this->formCheckbox($select);
                     ?><span class="lbl"></span>Usa lentes ?                      
                  </td>
                  
              </tr>
          </table>
            
         
            <hr />
              Es alergico a los siguientes elementos:
              <?php 
                  echo ($this->formRow($form->get('comenN')
                                              ->setAttribute("name", "alergias" ) ));
             ?>                           
            <hr />
              Operaciones o cirugias ?:
              <?php 
                  echo ($this->formRow($form->get('comenN')
                                              ->setAttribute("name", "operaciones" ) ));
             ?>                                         
            <hr />
              Enfermedades ?:
              <?php 
                  echo ($this->formRow($form->get('comenN')
                                              ->setAttribute("name", "operaciones" ) ));
             ?>                                         
              
      </div><!-- Fin Estado fisico -->   

      <div id="aficiones" class="tab-pane in active"><!-- Aficiones -->   
          
    
      </div><!-- Fin Aficiones -->   
        
   </div>
 </div>
</div>        
    
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    

<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    
