<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'o',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
         <?php          
           if ($dato["tipo"]==1){  // Predeterminado texto cuando no hay formularios anclados                ?>
      <tr> 
       <td><strong><?php echo $dato["nomAsp"] ?></strong></td>
       <td><?php echo $dato["nombre"]; ?></td>          
       <td>
         <?php          
               echo ($this->formRow($form->get('comenN')
                            ->setAttribute("name", "text".$dato["id"] )
                            ->setAttribute("value", $dato["texto"])  
                            ->setAttribute("class", ".span3" )));
         } // Fin valdiacion tipo 2?>                                   
       </td>   
     </tr> 
     <?php  if ($dato["tipo"]==2){  // Predeterminado texto cuando no hay formularios anclados  ?>
        <tr>
            <td><strong><?php echo $dato["nomAsp"] ?></strong></td>
            <td><?php echo $dato["nombre"] ?></td>
            <td>a
             <?php echo ($this->formRow($form->get('comenN')->setAttribute("name","comenNa".$dato["id"] )
                                                            ->setAttribute("value",$dato['a'])
                                                            ->setAttribute("class","span9")
                                                            ->setAttribute("value", $dato['a']) )); ?>
            </td>                            
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td>b
             <?php echo ($this->formRow($form->get('comenN')->setAttribute("name","comenNb".$dato["id"] )
                                                            ->setAttribute("value",$dato['b'])
                                                            ->setAttribute("class","span9")
                                                            ->setAttribute("value", $dato['b']))); ?>
            </td>                            
        </tr>        
        <tr>
            <td></td>
            <td></td>
            <td>c
             <?php echo ($this->formRow($form->get('comenN')->setAttribute("name","comenNc".$dato["id"] )
                                                            ->setAttribute("value",$dato['c'])
                                                            ->setAttribute("class","span9")
                                                            ->setAttribute("value", $dato['c']) )); ?>
            </td>                            
        </tr>        
        <tr>
            <td></td>
            <td></td>
            <td>d
             <?php echo ($this->formRow($form->get('comenN')->setAttribute("name","comenNd".$dato["id"] )
                                                            ->setAttribute("value",$dato['d'])
                                                            ->setAttribute("class","span9") 
                                                            ->setAttribute("value", $dato['d']) )); ?>
            </td>                            
        </tr>  
        <tr>
            <td></td>
            <td></td>
            <td>e
             <?php echo ($this->formRow($form->get('comenN')->setAttribute("name","comenNe".$dato["id"] )
                                                            ->setAttribute("value",$dato['e'])
                                                            ->setAttribute("class","span9")
                                                            ->setAttribute("value", $dato['e']) )); ?>
            </td>                            
        </tr>         
<?php }// Fin valdiacion tipo 4 ?>        
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>

<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
<?php    
    $name = $form->get('id2');
    echo $this->formInput($name);    
?>    
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php 
$this->lin = $this->lin.'i/'.$this->idCar;
echo $this->render('layout/iregresar') ?> 
