<?php echo $this->render('layout/titulo') ?>

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>            
            <td><?php echo $dato["id"] ?></td>
            <td><?php echo $dato["codigo"] ?></td>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["deno"] ?></td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>i/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/iitems') ?> </a>
            </td>                        
            <td>
                <?php // Parametros para impresion de documento 
                $this->idR = 19; // Id del reporte
                $this->idP = $dato["id"];
                echo $this->render('layout/ipdf'); // Fin parametros ?>
            </td>                                                   
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php 
$this->ncol='null,null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>     
