<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i/'.$this->id,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
<div class="col-sm-4">Nombre:<br />
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div> 
<div class="col-sm-4">Tipo:<br />
<?php
    $select = $form->get('tipo1');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div> 
<div class="col-sm-4"><br />
  <?php echo $this->formElement($form->get('agregar')) ?>
</div>  
</div>
<hr />
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    

<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
             <td><?php echo $dato["nomform"] ?></td>


            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>

           

<?php echo $this->render('layout/iregresar') ?> 