<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i/'.$this->id,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
<div class="col-sm-4">Nombre:<br />
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
<div class="col-sm-4">Tipo:<br />    
<?php
    $select = $form->get('tipo');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
<div class="col-sm-4">Definción de los tipos:<br />    
<?php
    $select = $form->get('ubicacion');
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>    
</div>    
</div>    
<hr />
<div class="row">    
<div class="col-sm-6">Definción de los tipos:<br />    
<?php 
    echo ($this->formRow($form->get('comenN')->setAttribute("class","span3") )); 
?>        
</div>
</div>

<div class="form-actions">    
  <?php echo $this->formElement($form->get('agregar')) ?>
</div>  
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<?php echo $this->form()->closeTag() ?>

<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["tipoN"] ?></td>
            <td><?php echo $dato["defNasp"] ?></td>            
            <td><?php // Si los tipos son 3 o 4 
            if ( ($dato["tipo"]==3) ){
            ?>    
               <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>o/<?php echo $dato["id"]?>"  target="_blank" > <?php echo $this->render('layout/iitems') ?> </a>              
            <?php    
            }else{
            echo $dato["lista"]; }?></td>            
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
  

<?php echo $this->render('layout/iregresar') ?> 