<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-4">
<?php
    $select = $form->get('idCcos')->setAttribute("id","idCcos");
    echo $formLabel->openTag().'Centro de costo';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
  </div>
  
<div class="col-sm-4">
<?php
    $select = $form->get('idCar')->setAttribute("id","idCar");
    echo $formLabel->openTag().$select->getLabel('Cargo');
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
<div class="col-sm-2">    
<?php
    $select = $form->get('cuotas');
    echo $formLabel->openTag().'Vacantes';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
<div class="col-sm-2">      
<?php
    $select = $form->get('estado');
    echo $formLabel->openTag() .'Estado';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
</div>

<br />

<div class="row">
    <div class="col-sm-4">
<?php
    $select = $form->get('idMot');
    echo $formLabel->openTag().$select->getLabel();
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
    <div class="col-sm-4">
<?php
    $select = $form->get('tipo');
    echo $formLabel->openTag().$select->getLabel();
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
    <div class="col-sm-3">        

<?php if ( $this->escala == 1 ){ // Manejo de escala salarial ?>
   Selecciona escala salarial :
   <?php //  
      $opciones = '';
      if ($this->datos!=''){
         foreach($this->datos as $dat){   
            $sel = '';  
            if ($this->idEsal == $dat['id'])
                $sel = "selected=selected" ;   
                $opciones = '<option '.$sel.' value="'.$dat['id'].'">'.$dat['salario'].'</option>';
          }
      }?>   
      <select name="idEsal" id="idEsal" ><?php echo $opciones ?></select>
<?php }else{ // Salario digitado ?>

    <div class="col-sm-6">
     <?php
        $name = $form->get('numero');
        echo $formLabel->openTag()."Digita el salario asignado : ";
        echo $formLabel->closeTag();
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
    ?>
    </div>
<?php } // Fin validacion si maneja escala salarial o no?>
</div>

</div>   
<hr />
<div class="row">
<div class="col-sm-6">
    Justificación:
    <?php echo ($this->formRow($form->get('comenN'))); ?>
</div>  
</div>    
<hr />
<div class="row">
<div class="col-sm-6">
    <?php echo ($this->formRow($form->get('comen'))); ?>
</div>  
</div>  

<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    

<script>      
$(function (){    
    $('#idCar').change(function(){    
        var id = $("#idCar").val();
        var parametros = {
               "id" : id,
            };  
        $.ajax({
            data:  parametros,		 
            url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>e',
            type:  'post',
            beforeSend: function () {
                $('#res').html('<option value="">Cargando...aguarde</option>')                
               },
            success:  function (response) {
                $('#idEsal').html(response);
            }
        });                        
    });        
})
</script>