<?php echo $this->render('layout/titulo') ?>

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["id"] ?></td>            
            <td><?php echo $dato["fecDoc"] ?></td>
            <td><?php echo $dato["fecApr"] ?></td>
            <td><?php echo $dato["nomSed"] ?></td>            
            <td><?php echo $dato["nomCcos"] ?></td>                        
            <td><?php echo $dato["nomCar"] ?></td>
            <td>
                <?php if ($dato["estado"]==0){ ?>
                   <?php echo $this->render('layout/ipendiente') ?>
                <?php } ?>
                <?php if ($dato["estado"]==1){ ?>
                   <?php echo $this->render('layout/iaprobado') ?>                
                <?php } ?>
            <td>
                <?php // Parametros para impresion de documento 
                $this->idR = 1; // Id del reporte
                $this->idP = $dato["id"];
                echo $this->render('layout/ipdf'); // Fin parametros ?>
            </td>                
            <td>
              <?php if ($dato["idCheq"]>0){ ?>  
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
              <?php } ?>                
            </td>
            <td>
               <?php if ($dato["estado"]==0){ ?> 
                 <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
               <?php } ?>  
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
    
<?php 
$this->ncol='null,null,null,null,null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>        